#!/bin/bash

set +e
rm -Rf apk_bin > /dev/null
mkdir -p apk_bin

repo="https://f-droid.org/repo/"

#downloadFromFdroid packageName overrides
downloadFromFdroid() {
	mkdir -p apk_tmp
    [ "$oldRepo" != "$repo" ] && rm -f apk_tmp/index.xml
    oldRepo="$repo"
	if [ ! -f apk_tmp/index.xml ];then
		#TODO: Check security keys
		wget --connect-timeout=10 $repo/index.jar -O apk_tmp/index.jar
		unzip -p apk_tmp/index.jar index.xml > apk_tmp/index.xml
	fi
	marketvercode="$(xmlstarlet sel -t -m '//application[id="'"$1"'"]' -v ./marketvercode apk_tmp/index.xml || true)"
	apk="$(xmlstarlet sel -t -m '//application[id="'"$1"'"]/package[versioncode="'"$marketvercode"'"]' -v ./apkname apk_tmp/index.xml || xmlstarlet sel -t -m '//application[id="'"$1"'"]/package[1]' -v ./apkname apk_tmp/index.xml)"
    if [ ! -f bin/$apk ];then
        while ! wget --connect-timeout=10 $repo/$apk -O apk_bin/$apk;do sleep 1;done
    fi
    echo "$apk wird installiert: "
    adb install apk_bin/$apk > /dev/null
    sleep 3
}

# install this apps
downloadFromFdroid org.fdroid.fdroid "F-Droid"
downloadFromFdroid org.fdroid.fdroid.privileged "F-Droid-Privileged"
# downloadFromFdroid ...

rm -Rf apk_tmp > /dev/null
rm -Rf apk_bin > /dev/null

echo "fine"
