#!/bin/bash

set +e

echo -n "
 install apps from F-Droid 
 -------------------------
 "

if [ $((`adb devices | grep -o "device" | wc -l`)) -ne 2 ]; then
	echo "please enable adb for exactly one device";
	exit;
fi

echo ""
echo "remove Linage Apps? y/n"
read
if [ "${REPLY}" = "y" ]; then 
	bash kill-Android-Apps.sh
fi

rm -Rf apk_bin > /dev/null
mkdir -p apk_bin

repo="https://f-droid.org/repo/"

#downloadFromFdroid packageName overrides
downloadFromFdroid() {
	mkdir -p apk_tmp
    [ "$oldRepo" != "$repo" ] && rm -f apk_tmp/index.xml
    oldRepo="$repo"
	if [ ! -f apk_tmp/index.xml ];then
		#TODO: Check security keys
		wget --connect-timeout=10 $repo/index.jar -O apk_tmp/index.jar
		unzip -p apk_tmp/index.jar index.xml > apk_tmp/index.xml
	fi
	marketvercode="$(xmlstarlet sel -t -m '//application[id="'"$1"'"]' -v ./marketvercode apk_tmp/index.xml || true)"
	apk="$(xmlstarlet sel -t -m '//application[id="'"$1"'"]/package[versioncode="'"$marketvercode"'"]' -v ./apkname apk_tmp/index.xml || xmlstarlet sel -t -m '//application[id="'"$1"'"]/package[1]' -v ./apkname apk_tmp/index.xml)"
    if [ ! -f bin/$apk ];then
        while ! wget --connect-timeout=10 $repo/$apk -O apk_bin/$apk;do sleep 1;done
    fi
    echo "$apk wird installiert: "
    adb install apk_bin/$apk > /dev/null
    sleep 1
}

echo ""
echo "remove AOSP keyboard and install anysoftkeyboard? y/n"
read
if [ "${REPLY}" = "y" ]; then 
	if downloadFromFdroid com.menny.android.anysoftkeyboard; then
		echo "okay"
		adb shell "su -c 'pm uninstall --user 0 com.android.inputdevices'"
		adb shell "su -c 'pm uninstall --user 0 com.android.inputmethod.latin'"
		downloadFromFdroid com.anysoftkeyboard.languagepack.SSH "A handy keyboard for terminal emulators, ssh clients ..."
	fi
fi

echo ""
echo "remove google-launcher and install Discreet-Launcher? y/n"
read
if [ "${REPLY}" = "y" ]; then 
	if downloadFromFdroid com.vincent_falzon.discreetlauncher; then
		echo "okay"
		adb shell "su -c 'pm uninstall --user 0 com.android.launcher3'"
	fi
fi

echo "This install Apps from F-Droid."
echo "--------------------------------------"
echo ""

# install this apps

#System
downloadFromFdroid org.fdroid.fdroid "F-Droid"
#downloadFromFdroid org.fdroid.fdroid.privileged "F-Droid-Privileged"
downloadFromFdroid com.machiav3lli.fdroid "Ein moderner F-Droid Client mit Material Design."
downloadFromFdroid me.phh.superuser "super user app"
downloadFromFdroid de.lukaspieper.gcam.services "Gcam Services Provider"
downloadFromFdroid me.zhanghai.android.files "material files manager"
downloadFromFdroid at.bitfire.davdroid "davdroid"
downloadFromFdroid ws.xsoh.etar "calendar"
downloadFromFdroid com.github.cvzi.screenshottile "Screenshots"
downloadFromFdroid com.kunzisoft.keepass.libre "keepass"
downloadFromFdroid com.secuso.privacyFriendlyCodeScanner "qr scanner"
downloadFromFdroid com.github.catfriend1.syncthingandroid "syncthing"
downloadFromFdroid com.github.tmo1.sms_ie "sms backup"
#downloadFromFdroid net.redwarp.gifwallpaper "Dein Lieblings-GIF als Live Wallpaper"
#downloadFromFdroid com.chooloo.www.koler "Telefonanwendung mit anpassbaren Funktionen"
downloadFromFdroid com.darshancomputing.BatteryIndicator "Shows your battery charge level"
downloadFromFdroid org.fsociety.vernet "Vernet - Network Analyzer Host and Port scanner. Ping IP or domain."
downloadFromFdroid org.connectbot "An SSH and telnet client, and terminal emulator for local shell."

downloadFromFdroid de.lukaspieper.gcam.services "Gcam Services Provider (Basic)"

downloadFromFdroid com.oF2pks.kalturadeviceinfos "kDI Device Info system permission"

downloadFromFdroid us.spotco.malwarescanner "FOSS-Malwarescanner"
downloadFromFdroid org.eu.exodus_privacy.exodusprivacy "Tracker und Berechtigungen in Apps"
downloadFromFdroid net.kollnig.missioncontrol.fdroid "tracker control"

# social
downloadFromFdroid eu.faircode.email "Fairmail"
#downloadFromFdroid security.pEp "Verschlüsselte E-Mails lesen und schreiben"
downloadFromFdroid com.twidere.twiderex "Nächste Generation von Twidere"
#downloadFromFdroid org.mariotaku.twidere "Twitter app"
#downloadFromFdroid com.jonjomckay.fritter "Fritter - Ein kostenloser, quelloffener Twitter-Client."
downloadFromFdroid com.plexer0.nitter "Nurlesender Twitter Client"
downloadFromFdroid nekox.messenger "telegram"
downloadFromFdroid com.keylesspalace.tusky "Mastodon"
downloadFromFdroid fr.gouv.etalab.mastodon "Mastodon"
downloadFromFdroid org.pixeldroid.app "Client for Pixelfed, the federated image sharing platform"

# monocles
#downloadFromFdroid de.monocles.mail "monocles mail ist ein Fork von K-9 Mail"
#downloadFromFdroid de.monocles.chat "ist ein Open Source XMPP/Jabber Messenger für Android"
#downloadFromFdroid de.monocles.browser "Ein Browser, der Ihre Privatsphäre schützt."
#downloadFromFdroid de.monocles.translator "monocles translator ein sicherer und privater Übersetzer"

# personal
downloadFromFdroid de.rki.covpass.app "covid pass"
downloadFromFdroid de.rki.covpass.checkapp "covid check"

# media
downloadFromFdroid net.sourceforge.opencamera "Open Camera"
downloadFromFdroid io.github.muntashirakon.Music "Best material design music player for Android"
#downloadFromFdroid org.schabi.newpipe "UTube"
downloadFromFdroid de.christinecoenen.code.zapp "Zapp Mediathek"
downloadFromFdroid com.foobnix.pro.pdf.reader "Bookreader"
downloadFromFdroid de.ph1b.audiobook "audio-book reader"
#downloadFromFdroid com.github.axet.bookreader "Book reader with a simple UI"
downloadFromFdroid de.danoeh.antennapod "Podcast"
downloadFromFdroid de.freehamburger "Client-App für die Nachrichten"

# browser
#downloadFromFdroid com.stoutner.privacybrowser.standard "Privacy Browser - Ein Browser, der Ihre Privatsphäre schützt"
#downloadFromFdroid threads.thor "Nativer IPFS and IPNS Browser welches auf WebKit-API basiert"
downloadFromFdroid org.mozilla.fennec_fdroid "Browser that supports current and anticipated web standards."
#downloadFromFdroid de.baumann.browser "FOSS Browser"
#downloadFromFdroid de.marmaro.krt.ffupdater "Updater für Firefox"
#downloadFromFdroid me.zhanghai.android.textselectionwebsearch "Add a \"Web search\" action to the text selection toolbar"
downloadFromFdroid com.example.deeplviewer "DeepL - inoffizielle Android App für den Deepl Translator"

#trafic
downloadFromFdroid de.schildbach.oeffi "Bus und Bahn"
downloadFromFdroid net.osmand.plus "Landkarte, Navi"
downloadFromFdroid app.organicmaps "Open-source, community-driven maps for travelers, tourists, cyclists & hikers"
downloadFromFdroid org.woheller69.lavatories "LavSeeker zeigt Toiletten die in OpenStreetMap eingetragen sind"

# game
downloadFromFdroid net.sourceforge.solitaire_cg "Solitaire"
downloadFromFdroid de.rwth_aachen.phyphox "Physik"

# other
downloadFromFdroid de.moekadu.tuner "guitar tuner"
#downloadFromFdroid de.kaffeemitkoffein.tinyweatherforecastgermany "Nice Wetter, Widget"
#downloadFromFdroid de.reimardoeffinger.quickdic "Offline Woerterliste"
downloadFromFdroid de.nucleus.foss_warn "Erhalte Notfallbenachrichtigungen von warnung.bund.de oder alert.swiss"


#downloadFromFdroid org.bromite.bromite "Bromite Browser"
# shell
#downloadFromFdroid com.smartpack.busyboxinstaller "busybox installer"
#downloadFromFdroid ru.meefik.busybox "busybox"

# simple tools
#downloadFromFdroid com.simplemobiletools.smsmessenger "simple sms"
#com.simplemobiletools.filemanager.pro "simple dateimanager"
#downloadFromFdroid com.simplemobiletools.contacts.pro "simple Contacts"
#downloadFromFdroid com.simplemobiletools.gallery.pro "simple Gallery"
#downloadFromFdroid com.simplemobiletools.musicplayer "simple musicplayer"
#downloadFromFdroid com.simplemobiletools.clock "simple clock"
#downloadFromFdroid com.simplemobiletools.dialer "simple dialer"
#downloadFromFdroid com.simplemobiletools.calendar.pro "simple calendar"
#downloadFromFdroid com.termux "terminal"
#downloadFromFdroid com.termux.gui "GUI terminal"
#downloadFromFdroid org.smssecure.smssecure "SMS"
#downloadFromFdroid net.typeblog.shelter "Isolate your Big Brother Apps"
#downloadFromFdroid com.securefilemanager.app "dateimanager"
#downloadFromFdroid com.menny.android.anysoftkeyboard "anysoftkey"

#downloadFromFdroid com.qualcomm.location 
#downloadFromFdroid com.machiav3lli.backup "backup"
#downloadFromFdroid org.gateshipone.odyssey "Music Player"
downloadFromFdroid org.videolan.vlc "vlc"
#downloadFromFdroid com.simplemobiletools.filemanager.pro "dateimanager"
#downloadFromFdroid com.securefilemanager.app "dateimanager"
#downloadFromFdroid cx.vmx.sdcontacts "Kontakte offline sichern"
#downloadFromFdroid com.dosse.speedtest "Speedtest"

#YouTube viewer
repo=https://archive.newpipe.net/fdroid/repo/
downloadFromFdroid org.schabi.newpipe "Schlanke YouTube-Oberfläche"
	

echo "Install Neo Launcher? y/n"
read
if [ "${REPLY}" = "y" ]; then
	repo=https://apt.izzysoft.de/fdroid/repo
	downloadFromFdroid com.saggitt.omega "Neo 3 Launcher"
fi
	
echo "Install microg? y/n"
read
if [ "${REPLY}" = "y" ]; then	
	repo=https://microg.org/fdroid/repo/
	downloadFromFdroid com.google.android.gms
	downloadFromFdroid com.google.android.gsf
	downloadFromFdroid com.android.vending
fi

echo "Install Bromite? y/n"
read
if [ "${REPLY}" = "y" ]; then
	repo=https://fdroid.bromite.org/fdroid/repo/
	downloadFromFdroid org.bromite.bromite "Browser2 QuickSearchBox"
	downloadFromFdroid org.bromite.webview "WebView webview"
fi

echo -e "\n install extra lokale apps \n"

for file in ./Apps/*.apk
do
  	echo "install $file? y/n"
	read
	if [ "${REPLY}" = "y" ]; then
		adb install $file
	fi
done 

rm -rf apk_tmp/ > /dev/null

echo "Downloads (*.apk) loeschen? y/n"
read
if [ "${REPLY}" = "y" ]; then
	rm -rf apk_bin/ > /dev/null
fi

echo "fine"
