#!/bin/bash

#Usage:
#bash sudo OpenImage.sh Mountpoint[Variable/String] [/path/to/system/image]

if [ "$(whoami)" != "root" ]; then
	echo  "You are not root!!!"
	echo "Usage:"
	echo "sudo bash OpenImage.sh /path/to/system/image"
	exit
fi

if [ ! -e "$1" ]; then
	echo "Error: No Image!"
	echo "/path/to/system/image Faulty or missing!"
	exit
fi

echo "Type 'm' für mount image"
echo "Type 'u' für unmount image"
read run
echo "$1"

#set -ex

if [ "$run" = "m" ]; then
	#cleanups
	umount Image &> /dev/null
	touch .Imagename && echo "$1" > .Imagename
	echo "MOUNT"
	rm -Rf tmp Image
	mkdir -p tmp Image 
	simg2img $1 I.img || cp $1 I.imgg
	e2fsck -n I.img > /dev/null
	if [ $? -eq 0 ]; then 
		echo "Image I.img okay"
		e2fsck -y -f I.img
		resize2fs I.img 3500M
		e2fsck -E unshare_blocks -y -f I.img
		mount -o loop,rw I.img Image
	fi

	e2fsck -n I.imgg > /dev/null
	if [ $? -eq 0 ]; then 
		echo "Image I.imgg okay"
		e2fsck -y -f I.img
		resize2fs I.imgg 3500M
		e2fsck -E unshare_blocks -y -f I.imgg
		mount -o loop,rw I.imgg Image
	fi
elif [ "$run" = "u" ]; then
	echo ""
	echo "Kill default Apps and make the new System clean? y/n"
	read
	if [ "${REPLY}" = "y" ]; then
		sudo bash kill_AppsFromImage.sh
	fi
	
	echo ""
	if [ ! -e Image/system/phh/secure ]; then
		echo "Do you want to remove 'superuser'? y/n"
		read
		if [ "${REPLY}" = "y" ]; then	
			touch Image/system/phh/secure
			rm Image/system/xbin/su
			rm Image/system/bin/phh-su
			rm Image/system/etc/init/su.rc
			rm Image/system/bin/phh-securize.sh
			rm -Rf Image/system/{app,priv-app}/me.phh.superuser/
		fi
	fi
		
	echo "UnMount"
	umount Image
	sleep 1
	
	touch NewImage.img
	DEVICES=$(adb devices | grep "device$" | sed -e "s|device||g")
	echo $DEVICES
	echo "Write changes? y/n"
	read
	if [ "${REPLY}" != "y" ]; then exit; fi 
		e2fsck -n I.img > /dev/null
		if [ $? -eq 0 ]; then 
			e2fsck -f -y I.img || true
			resize2fs -M I.img
			sleep 1
			cp I.img New-Image.img
		fi
		e2fsck -n I.imgg > /dev/null
		if [ $? -eq 0 ]; then 
			e2fsck -f -y I.imgg || true
			resize2fs -M I.imgg
			sleep 1
			cp I.imgg New-Image.img
		fi
	rm -f .Imagename
		
	echo ""
	echo "Copy to Mobil SDCard and restart to TRWP? y/n"
	read
	if [ "${REPLY}" = "y" ]; then
		if [ "$DEVICES" = "" ]; then
			echo "No Devices over adb detected"
			echo "Stop. Now activate adb and continue."
			echo " Enter for continue"
			read
		fi
		echo ""
		echo "Detected $DEVICES on adb"
		echo ""
		adb push NewImage.img /sdcard && adb reboot recovery
	fi
fi 

echo "fine"

exit
