#!/bin/bash

#Usage:
#bash sudo OpenImage.sh Mountpoint[Variable/String] [/path/to/system/image]

if [ "$(whoami)" != "root" ]; then
	echo  "You are not root!!!"
	echo "Usage:"
	echo "sudo bash OpenImage.sh /path/to/system/image"
	exit
fi

if [ ! -e "$1" ]; then
	echo "Error: No Image!"
	echo "/path/to/system/image Faulty or missing!"
	exit
fi

echo "Type 'm' für mount image"
echo "Type 'u' für unmount image"
read run
echo "$1"

#set -ex
touch .Imagename && echo "$1" > .Imagename
Image="$(cat .Imagename)"
BaseName="$(basename $Image .img)"
DirName="Dir_$BaseName"
MountImg="Mount_$BaseName"
NewImage="New_$BaseName"


if [ "$run" = "m" ]; then
	#cleanups
	umount $DirName &> /dev/null
	echo "MOUNT"
	rm -Rf tmp $BaseName
	mkdir -p tmp $DirName
	simg2img $Image $MountImg.img || cp $Image $MountImg.imgg
	e2fsck -n $MountImg.img > /dev/null
	if [ $? -eq 0 ]; then 
		echo "Image I.img okay"
		e2fsck -y -f $MountImg.img
		resize2fs $MountImg.img 3500M
		e2fsck -E unshare_blocks -y -f $MountImg.img
		mount -o loop,rw $MountImg.img $DirName
	fi

	e2fsck -n $MountImg.imgg > /dev/null
	if [ $? -eq 0 ]; then 
		echo "Image I.imgg okay"
		e2fsck -y -f $MountImg.img
		resize2fs $MountImg.imgg 3500M
		e2fsck -E unshare_blocks -y -f $MountImg.imgg
		mount -o loop,rw $MountImg.imgg $DirName
	fi
elif [ "$run" = "u" ]; then
	echo ""
	echo "Kill default Apps and make the new System clean? y/n"
	read
	if [ "${REPLY}" = "y" ]; then
		sudo bash kill_AppsFromImage.sh
	fi
	
	echo ""
	if [ ! -e $Image/system/phh/secure ]; then
		echo "Do you want to remove 'superuser'? y/n"
		read
		if [ "${REPLY}" = "y" ]; then	
			touch $DirName/system/phh/secure
			rm $DirName/system/xbin/su
			rm $DirName/system/bin/phh-su
			rm $DirName/system/etc/init/su.rc
			rm $DirName/system/bin/phh-securize.sh
			rm -Rf $DirName/system/{app,priv-app}/me.phh.superuser/
		fi
	fi
	
	echo "Pause. Controll yor changes."
	read
	
	echo "UnMount"
	umount $DirName
	sleep 1
	
	touch $NewImage.img
	DEVICES=$(adb devices | grep "device$" | sed -e "s|device||g")
	echo $DEVICES
	echo "Write changes? y/n"
	read
	if [ "${REPLY}" != "y" ]; then exit; fi 
		e2fsck -n $MountImg.img > /dev/null
		if [ $? -eq 0 ]; then 
			e2fsck -f -y $MountImg.img || true
			resize2fs -M $MountImg.img
			sleep 1
			cp $MountImg.img $NewImage.img
		fi
		e2fsck -n $MountImg.imgg > /dev/null
		if [ $? -eq 0 ]; then 
			e2fsck -f -y $MountImg.imgg || true
			resize2fs -M $MountImg.imgg
			sleep 1
			cp $MountImg.imgg $NewImage.img
		fi
	sleep 1
	rm -f Mount_*.img*
	rm -r Dir_*
		
	echo ""
	echo "Copy to Mobil SDCard and restart to TRWP? y/n"
	read
	if [ "${REPLY}" = "y" ]; then
		if [ "$DEVICES" = "" ]; then
			echo "No Devices over adb detected"
			echo "Stop. Now activate adb and continue."
			echo " Enter for continue"
			read
		fi
		echo ""
		echo "Detected $DEVICES on adb"
		echo ""
		adb push $NewImage.img /storage/3B43-1220 && adb reboot recovery
		#adb push NewImage.img /sdcard && adb reboot recovery
	fi
fi 

echo "fine"

exit
